all:
	g++ a.cpp -o a \
	-I/home/jiao/Software/Boost-1.85.0/include \
	-L/home/jiao/Software/Boost-1.85.0/lib && \
	g++ b.cpp -o b \
	-I/home/jiao/Software/Boost-1.85.0/include \
	-L/home/jiao/Software/Boost-1.85.0/lib